/* SPDX-License-Identifier: GPL-2.0+ */

#ifndef __LAN966X_CONFIG_H
#define __LAN966X_CONFIG_H

#define CONFIG_ARCH_CPU_INIT

#define CONFIG_BOARD_TYPES
#define CONFIG_SUPPORT_EMMC_BOOT

#define CONFIG_BOOTP_BOOTFILESIZE
#define PHY_ANEG_TIMEOUT                20000

#define CONFIG_SYS_SDRAM_BASE           0x60200000
#define CFG_SYS_INIT_RAM_ADDR           CONFIG_SYS_SDRAM_BASE
#define CFG_SYS_INIT_RAM_SIZE           0x400000

#if defined(CONFIG_TARGET_LAN966X_EVB)
#define DDR_MEM_SIZE 0x40000000
#elif defined(CONFIG_TARGET_LAN966X_SVB)
#define DDR_MEM_SIZE 0x80000000
#endif

#define CFG_SYS_SDRAM_BASE              CONFIG_SYS_SDRAM_BASE
#define CONFIG_SYS_SDRAM_SIZE (DDR_MEM_SIZE - (2 * 1024 * 1024))

#define CONFIG_SYS_MMC_ENV_DEV		0

#endif
